Cloud SDK: Tutorial to integrate with CAP Framework
SAPDocuments/Tutorials pull request #5835
Opened 2020-09-10 13:56 UTC by MatKuhr

This PR is a replacement for #5739 with the same content.

2020-09-10 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAPDocuments/Tutorials?pullRequest=5835) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAPDocuments/Tutorials?pullRequest=5835) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAPDocuments/Tutorials?pullRequest=5835) it.</sub>

2020-09-15 07:31 UTC, sacnl commented
@thecodester 
As this has been discussed in the previous pull request, I assume this is good to go?
As we already had users asking for this tutorial, I would like to merge this by tomorrow EOB, unless you see open issues.

2020-09-17 07:55 UTC, MichaelCzcz requested changes
This tutorial has an unreachable link in line 48.
It also has outdated author information (Nabil shafi is no longer with SAP).
Please update the tutorial and validate it using the Atom plugin.

2020-09-17 08:03 UTC, MatKuhr commented
> This tutorial has an unreachable link in line 48.

Please check again, for me this link is reachable. 

> It also has outdated author information (Nabil shafi is no longer with SAP).

How can I change the author information? I already changed the commits such that only I occur in the commit history.

> Please update the tutorial and validate it using the Atom plugin.

Validation is successful with my plugin.

2020-09-18 08:21 UTC, MichaelCzcz requested changes

2020-09-18 08:21 UTC, MichaelCzcz commented on tutorials/cloudsdk-integrate-cap/cloudsdk-integrate-cap.md
> +In particular, you will learn how to integrate the SAP Cloud SDK into the SAP Cloud Application Programming Model. And how SAP Cloud SDK allow you to develop, extend and communicate with other SAP so
```suggestion
In particular, you will learn how to integrate the SAP Cloud SDK into the SAP Cloud Application Programming Model. And how SAP Cloud SDK allows you to develop, extend and communicate with other SAP solutions.
```

2020-09-18 08:21 UTC, MichaelCzcz commented on tutorials/cloudsdk-integrate-cap/cloudsdk-integrate-cap.md
> +    Here we are using the OData VDM from SAP Cloud SDK to fetch business partners from the target system. We can call this service `getAllBusinessPartner()` function to retrieve a list of all the bus
Always say "you will" or "your system", never "we".

Please change all occurrences accordingly.
Please see the style guide for more details: https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9

2020-09-18 08:21 UTC, MichaelCzcz commented on tutorials/cloudsdk-integrate-cap/cloudsdk-integrate-cap.md
> +    Later we transform `BusinessPartner` to `CapBusinessPartner` according to our requirements.
Always say "you will" or "your system", never "we".

Please change all occurrences accordingly.

2020-09-18 11:22 UTC, MatKuhr commented
I addressed the changes and also added my GH profile as author profile.

2020-09-18 12:46 UTC, merged