updated ticket info
SAPDocuments/Tutorials pull request #5928
Opened 2020-10-04 08:52 UTC by Paolaufer

2020-10-04 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAPDocuments/Tutorials?pullRequest=5928) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAPDocuments/Tutorials?pullRequest=5928) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAPDocuments/Tutorials?pullRequest=5928) it.</sub>

2020-10-05 06:43 UTC, MichaelCzcz requested changes
Just some minor things to keep those lines consistent with the other ones.

2020-10-05 06:43 UTC, MichaelCzcz commented on tutorials/appstudio-cap-deploy-app/appstudio-cap-deploy-app.md
> +    2. Go to **Service Marketplace**
```suggestion
    2. Go to **Service Marketplace**.
```

2020-10-05 06:43 UTC, MichaelCzcz commented on tutorials/appstudio-cap-deploy-app/appstudio-cap-deploy-app.md
> +    2. Go to **Service Marketplace**
```suggestion
    2. Go to **Service Marketplace**.
```

2020-10-05 06:43 UTC, MichaelCzcz commented on tutorials/appstudio-cap-deploy-app/appstudio-cap-deploy-app.md
> +    3. Select **SAP HANA Schemas & HDI Containers (SAP HANA Trial)**
```suggestion
    3. Select **SAP HANA Schemas & HDI Containers (SAP HANA Trial)**.
```

2020-10-05 09:02 UTC, Paolaufer commented
added your comments

2020-10-05 09:11 UTC, merged