MDK Mission tutorials- level up with MDK
SAPDocuments/Tutorials pull request #6100
Opened 2020-10-31 17:25 UTC by jitendrakansal

updated MDK Mission tutorials- level up with MDK
https://developers.sap.com/mission.mobile-dev-kit-level-up.html

2020-10-31 21:39 UTC, jitendrakansal commented
updated tutorials for other two missions as well:

- https://developers.sap.com/mission.mobile-dev-kit-brand.html
- https://developers.sap.com/mission.mobile-dev-kit-controls.html

2020-11-02 08:15 UTC, MichaelCzcz requested changes
There are some "missing words" errors and small style issues. For your convenience, I have made suggestions on how it should look like. You can either make the changes in your fork and push them to production or you can click "Commit suggestion", but you will have to apply them manually to QA.

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-error-archive/cp-mobile-dev-kit-error-archive.md
> +7. After clicking **Finish**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_ErrorArchive` project in the project explorer. As you have already op
```suggestion
7. After clicking **Finish**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_ErrorArchive` project in the project explorer. As you have already opened the workspace, there is no need to open the generated project in a new workspace. Ignore the pop-up or click the cross icon to hide the window.
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-map-extension/cp-mobile-dev-kit-map-extension.md
> +7. After clicking **Finish**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Maps` project in the project explorer. As you have already opened the
```suggestion
7. After clicking **Finish**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Maps` project in the project explorer. As you have already opened the workspace, there is no need to open the generated project in a new workspace. Ignore the pop-up or click the cross icon to hide the window.
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-nativescript-geolocation/cp-mobile-dev-kit-nativescript-geolocation.md
> +5. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Geolocation` project in the project explorer. As you have already opene
```suggestion
5. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Geolocation` project in the project explorer. As you have already opened the workspace, there is no need to open the generated project in a new workspace. Ignore the pop-up or click the cross icon to hide the window.
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-online-app/cp-mobile-dev-kit-online-app.md
> +6. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDKOnlineApp` project in the project explorer. As you have already opened t
```suggestion
6. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDKOnlineApp` project in the project explorer. As you have already opened the workspace, there is no need to open the generated project in a new workspace. Ignore the pop-up or click the cross icon to hide the window.
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-push/cp-mobile-dev-kit-push.md
> +5. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Push` project in the project explorer. As you have already opened the w
```suggestion
5. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Push` project in the project explorer. As you have already opened the workspace, there is no need to open the generated project in a new workspace. Ignore the pop-up or click the cross icon to hide the window.
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-rest-api/cp-mobile-dev-kit-rest-api.md
> +5. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Petstore` project in the project explorer. As you have already opened t
```suggestion
5. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Petstore` project in the project explorer. As you have already opened the workspace, there is no need to open the generated project in a new workspace. Ignore the pop-up or click the cross icon to hide the window.
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-rest-api/cp-mobile-dev-kit-rest-api.md
> +4. Under `Body`, switch to `object type` by clicking on the icon, once it's color has changed click on `Body[0]` to add array items, this should now display a create icon in front of `Body[0]`. Click
```suggestion
4. Under `Body`, switch to `object type` by clicking the icon, once it's color has changed click `Body[0]` to add array items, this should now display a create icon in front of `Body[0]`. Click Create icon to create an array item(0).
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-slider-extension/cp-mobile-dev-kit-slider-extension.md
> +To extend the functionality, or customize the look and feel, and behavior of your client app, you can create extension controls other than the already existing MDK built-in controls using **NativeScr
```suggestion
To extend the functionality, or customize the look and feel, and behavior of your client app, you can create extension controls other than the already existing MDK built-in controls by using **NativeScript** (TypeScript/JavaScript applicable for both Android and iOS)
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-slider-extension/cp-mobile-dev-kit-slider-extension.md
> +5. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Slider` project in the project explorer. As you have already opened the
```suggestion
5. After clicking **Next**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Slider` project in the project explorer. As you have already opened the workspace, there is no need to open the generated project in a new workspace. Ignore the pop-up or click the cross icon to hide the window.
```

2020-11-02 08:15 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-style/cp-mobile-dev-kit-style.md
> +9. After clicking **Finish**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Styling` project in the project explorer. As you have already opened
```suggestion
9. After clicking **Finish**, the wizard will generate your MDK Application based on your selections. You should now see the `MDK_Styling` project in the project explorer. As you have already opened the workspace, there is no need to open the generated project in a new workspace. Ignore the pop-up or click the cross icon to hide the window.
```

2020-11-02 18:46 UTC, jitendrakansal commented
@MichaelCzcz thanks for reviewing, i'have updated the tutorials with your feedback.

2020-11-03 08:15 UTC, MichaelCzcz commented
Please check the links in all tutorials that are part of this mission and change them to the correct formatting where necessary.
Please also check the formatting, for example, spacing and indentation for images, of all tutorials and adjust it where necessary. For details please see the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqfqchq1u).

2020-11-03 08:43 UTC, jitendrakansal commented
@MichaelCzcz I didn't follow you completely.
Could you point me to one tutorial which does not have link in correct format so that i can update it in others?

2020-11-03 10:59 UTC, jitendrakansal commented
@MichaelCzcz i have updated the PR with changes as we discussed in the call. Please check now.

2020-11-03 12:39 UTC, MichaelCzcz requested changes
I have found more cases where the links are not formatted correctly. Also, please don't link to tutorial steps. Rather link to the tutorial and name the step in the text. Please make corrections.
https://github.com/SAPDocuments/Tutorials/blame/a6f757e0f01115c5887678b2fca87d14aae5eea4/tutorials/cp-mobile-dev-kit-annotations/cp-mobile-dev-kit-annotations.md#L45
https://github.com/SAPDocuments/Tutorials/blame/a6f757e0f01115c5887678b2fca87d14aae5eea4/tutorials/cp-mobile-dev-kit-build-client/cp-mobile-dev-kit-build-client.md#L185
https://github.com/SAPDocuments/Tutorials/blame/a6f757e0f01115c5887678b2fca87d14aae5eea4/tutorials/cp-mobile-dev-kit-build-client/cp-mobile-dev-kit-build-client.md#L257
https://github.com/SAPDocuments/Tutorials/blame/a6f757e0f01115c5887678b2fca87d14aae5eea4/tutorials/cp-mobile-dev-kit-link-entity/cp-mobile-dev-kit-link-entity.md#L23

2020-11-03 13:52 UTC, jitendrakansal commented
@MichaelCzcz i have pushed the changes as per your last comment, please check now.

2020-11-03 14:24 UTC, merged