missions overhaul
SAPDocuments/Tutorials pull request #6112
Opened 2020-11-04 17:06 UTC by KevinMuessig

2020-11-05 07:56 UTC, MichaelCzcz requested changes
I have made some comments regarding grammar etc.
There are also many style issues.
There are many cases where you have to use You and not the royal We. (unless, in rare cases, you are referring to SAP). I haven't pointed out each and everyone of them, because they are just too many of them. So, please check by yourself and make the necessary corrections.

There are also many cases of "click on <thing to be clicked>", where it would be better to just say "click <thing to be clicked> or use other words like "select" or "choose", but these are not that important. It would be nice if you could change them, but it is not mandatory.

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-04/fiori-ios-scpms-starter-mission-04.md
> +    If you compile now, there shouldn't be any compile time errors, if you get a compile time error for the `odataController` remember to make the `import SAPOfflineOData` import statement. What you
"What you basically did is pasted a modified code copied"
Please correct grammar.

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-06/fiori-ios-scpms-starter-mission-06.md
> +In the beginning we want to change the app flow to have a split view in place when running on Mac Catalyst. The split view or Split View allows Mac Catalyst to display a sidebar similar to Apple's Mu
Please stick to the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd) and don't say "we", but say "you" instead.

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-06/fiori-ios-scpms-starter-mission-06.md
> +    Because the Main View Controller is the new initial view controller we have to change the `ApplicationUIManager` code accordingly.
Please stick to the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd) and don't say "we", but say "you" instead.

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-06/fiori-ios-scpms-starter-mission-06.md
> +5. Important is that you set an identity for the original **Navigation Controller**. In the `Main.storyboard`, click on the Navigation Controller which is the detail view controller for the split vie
"It is important that..."

Please stick to the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd) and don't say "click on". In this case "select the Navigation Controller" would be better.
Please add missing comma before "which".

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-06/fiori-ios-scpms-starter-mission-06.md
> +6. The last step we want to do is change the navigation item's title from **`SidebarTableViewController`** to **Navigation**. Add the following line of code to the `viewDidLoad()` method:
Say "you" instead of "we".

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-teched19-01/fiori-ios-scpms-teched19-01.md
> +2. You will create a new native application cloud configuration on Mobile Services. To do so click on **Native/Hybrid** on the left-hand side and then on **New**.
"To do so click on **Native/Hybrid**"
or
"To do so choose **Native/Hybrid**"

"...side and then click **New**."

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-teched19-01/fiori-ios-scpms-teched19-01.md
> +3. In the upcoming dialogue enter the following values and click on **Next**.
"click **Next**"

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-02/fiori-ios-scpms-starter-mission-02.md
>  4. Before we can start dequeuing the needed cells, complete the `viewDidLoad()` method:
Please don't say "we", say "you" instead as described in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd).

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-02/fiori-ios-scpms-starter-mission-02.md
>      To conform to these protocols we will implement a class extension where we will implement the protocol methods.
Please don't say "we", say "you" instead as described in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd).

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-03/fiori-ios-scpms-starter-mission-03.md
> +    /// Create a computed property that uses the OnboardingSessionManager to retrieve the onboarding session and uses the destinations dictionary to pull the correct destination. Of course we only ha
Please don't say "we", say "you" instead as described in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd).

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-03/fiori-ios-scpms-starter-mission-03.md
>      You might wonder why we are not passing the data service in from the Overview. Later on when adapting the app to work on MacOS through Mac Catalyst, the user will have the option to jump directly
Please don't say "we", say "you" instead as described in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd).

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-03/fiori-ios-scpms-starter-mission-03.md
>  3. The code won't compile at the moment because you haven't conformed to the `UISearchResultsUpdating` protocol. We will fix that at a later point but first call the `setupSearchBar()` method right b
Please don't say "we", say "you" instead as described in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd).

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-04/fiori-ios-scpms-starter-mission-04.md
>      Also, the `loadProductImages()` method is not necessary anymore so we deleted that.
Please don't say "we", say "you" instead as described in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd).

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-06/fiori-ios-scpms-starter-mission-06.md
> +In the beginning we want to change the app flow to have a split view in place when running on Mac Catalyst. The split view or Split View allows Mac Catalyst to display a sidebar similar to Apple's Mu
Please don't say "we", say "you" instead as described in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd).

2020-11-05 07:56 UTC, MichaelCzcz commented on tutorials/fiori-ios-scpms-starter-mission-06/fiori-ios-scpms-starter-mission-06.md
>      Let's quickly go over what we did here. First we added a new Split View Controller which is a standard Apple UI control. Then we added our app flow to the Split View Controller through a **detail
Please don't say "we", say "you" instead as described in the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtqgno1sd).

2020-11-11 13:28 UTC, KevinMuessig commented
@MichaelCzcz Could you please confirm the changes so we can push this to production?

2020-11-12 08:21 UTC, merged