Improve SAP Cloud SDK CI/CD tutorial and adapt it to use the General Purpose Pipeline of project "Piper"
SAPDocuments/Tutorials pull request #6215
Opened 2020-11-19 16:16 UTC by daniel-kurzynski

2020-11-19 16:19 UTC, daniel-kurzynski commented on tutorials/cloudsdk-e2e-test-secure-applications/cloudsdk-e2e-test-secure-applications.md
> +  - [Set up CI/CD](cloudsdk-ci-cd)
@thecodester These changes are already merged to master. Not sure how they made it into this PR.

2020-11-19 16:26 UTC, daniel-kurzynski commented on tutorials/cloudsdk-e2e-test-secure-applications/cloudsdk-e2e-test-secure-applications.md
> +  - [Set up CI/CD](cloudsdk-ci-cd)
Fixed by cleaning up the git history.

2020-11-20 08:32 UTC, thecodester requested changes
Looks good. 

- The description is too long. If you want to say more, just put it in the intro -- intro starts by skipping line after Your will learn items and then writing whatever you want. Too long description gets cut off on the tutorial tile.

- In Step 3 you have 2 images side by side -- about blue ocean UI. Is that how you want them to appear?

2020-11-20 10:34 UTC, daniel-kurzynski commented
> Looks good.
> 
> * The description is too long. If you want to say more, just put it in the intro -- intro starts by skipping line after Your will learn items and then writing whatever you want. Too long description gets cut off on the tutorial tile.
> * In Step 3 you have 2 images side by side -- about blue ocean UI. Is that how you want them to appear?

Thanks for the feedback. Karsten told me that the description should be a bit longer and more speaking. But I now have a little shorter one. 
Please review again.

2020-11-20 11:41 UTC, thecodester commented
The description is a 1-sentence, 20-25 word shorthand of what the user will do in the tutorial. It is for the tile, so the tile can only show so much and you want to avoid forcing the user to click in. If you need more information, you can write as much as you need in the intro.

Start the description with the word "Use ..." -- it  reduce the number of words by 25% and get right to the point. After that I will merge.

I am checking the QA version.

2020-11-20 12:02 UTC, thecodester commented
Also notice that the code sample (YAML) first one in Step 7 displays very large in the preview -- not sure how you want to fix, but if you put a blank line after the start backticks it fixes this. Don;t think this is why it did not publish but I will take a look on Sunday.

2020-11-20 12:43 UTC, daniel-kurzynski commented
> The description is a 1-sentence, 20-25 word shorthand of what the user will do in the tutorial. It is for the tile, so the tile can only show so much and you want to avoid forcing the user to click in. If you need more information, you can write as much as you need in the intro.
> 
> Start the description with the word "Use ..." -- it reduce the number of words by 25% and get right to the point. After that I will merge.
> 
> I am checking the QA version.

Done

2020-11-24 10:11 UTC, merged