Automatic commit: Move 'iot-model-create', 'iot-onboard-device', 'iot…
SAPDocuments/Tutorials pull request #6430
Opened 2021-01-21 16:13 UTC by marcuscbehrens

…-cf-consume-measures', 'iot-cf-create-device-model-api', 'iot-cf-create-user-tenant', 'iot-cf-enable-iot-service', 'iot-cf-install-curl', 'iot-cf-install-openssl', 'iot-cf-install-paho-client', 'iot-cf-send-commands-mqtt', 'iot-cf-send-data-mqtt', 'iot-cf-send-data-rest', 'iot-ds-1-define-actions', 'iot-ds-2-create-flp', 'iot-ds-3-create-ui', 'iot-ds-4-build-test', 'iot-ds-5-view-ext', 'iot-edge-plant-maintenance-1', 'iot-edge-plant-maintenance-2', 'iot-express-1-buy-sapstore', 'iot-express-2-create-device-model', 'iot-express-3-configure-device', 'iot-express-4-create-thing-model', 'iot-express-4a-define-rule-action', 'iot-express-5-use-webide-template', 'iot-locations-geofence', 'iot-locations-geomatch', 'iot-sac-integration-ext', 'iotae-api-nodejs-events', 'iotae-api-postman', 'iotae-comp-analyticalodata' from QA to Production

2021-01-22 07:10 UTC, MichaelCzcz requested changes

2021-01-22 07:10 UTC, MichaelCzcz commented on tutorials/iot-sac-integration-ext/iot-sac-integration-ext.md
> +    Upon updating the Postman environment parameters successfully, you are done with the Postman set up.
The old version was correct.

the setup
to set up

2021-01-22 07:10 UTC, MichaelCzcz commented on tutorials/iot-sac-integration-ext/iot-sac-integration-ext.md
> +1.	Open your licensed SAP Analytics Cloud tenant URL and login with valid credentials that are assigned with right roles that authorise to create live connection, create models and stories.
Same thing here:

the login
to log in

2021-01-25 11:57 UTC, marcuscbehrens commented
I have done the changes (again). Somehow the Q-Version was not up to date – someone has done changes to the live version without updating the q-version earlier.

2021-01-25 14:14 UTC, merged