Branding Updates
SAPDocuments/Tutorials pull request #6467
Opened 2021-02-04 13:05 UTC by nedo-SAP

2021-02-04 14:01 UTC, MichaelCzcz requested changes
Please make sure to use the correct spelling of product names.

https://wiki.wdf.sap.corp/wiki/display/NDW/SAP+BTP%3A+Rebranding+Guidelines

2021-02-04 14:01 UTC, MichaelCzcz commented on tutorials/cp-cf-security-xsuaa-multi-tenant/cp-cf-security-xsuaa-multi-tenant.md
> +3. Open the SAP BTP Cockpit.
SAP BTP cockpit

2021-02-04 14:01 UTC, MichaelCzcz commented on tutorials/cp-cf-security-xsuaa-create/cp-cf-security-xsuaa-create.md
> +3. Open the SAP BTP Cockpit.
SAP BTP cockpit

2021-02-05 07:02 UTC, nedo-SAP commented on tutorials/cp-cf-security-xsuaa-multi-tenant/cp-cf-security-xsuaa-multi-tenant.md
> +1. Open the [SAP BTP trial](https://account.hanatrial.ondemand.com/cockpit/#/home/trialhome).
fixed

2021-02-05 07:02 UTC, nedo-SAP commented on tutorials/cp-cf-security-xsuaa-multi-tenant/cp-cf-security-xsuaa-multi-tenant.md
> +3. Open the SAP BTP Cockpit.
fixed

2021-02-05 07:02 UTC, nedo-SAP commented on tutorials/cp-cf-security-xsuaa-create/cp-cf-security-xsuaa-create.md
> +3. Open the SAP BTP Cockpit.
fixed

2021-02-05 08:33 UTC, merged