Incorporating Rebranding Changes for Mobile Cards, iOS SDK & Android SDK
SAPDocuments/Tutorials pull request #6555
Opened 2021-03-04 18:47 UTC by sandeep-tds

Made the following changes:

replace "software-product-function>sap-cloud-platform-mobile-services"
with "products>sap-mobile-services"

replace "products>sap-cloud-platform"
with "products>sap-business-technology-platform"

replace "products>sap-cloud-platform-for-the-cloud-foundry-environment"
with "products>sap-btp-cloud-foundry-environment"

replace "SAP Cloud Platform SDK for iOS"
with "SAP BTP SDK for iOS"

replace "SAP BTP SDK for iOS Assistant"
with "SAP BTP SDK Assistant for iOS"

replace "SAP Cloud Platform SDK for Android"
with "SAP BTP SDK for Android"

replace "SAP Cloud Platform SDK for Android Wizard"
with "SAP BTP SDK Wizard for Android"

replace "SAP Cloud Platform Mobile Services"
with "SAP Mobile Services"

replace "SAP Cloud Platform Mobile Service"
with "SAP Mobile Services"

replace "SAP Cloud Platform"
with "SAP BTP"

replace "SCP"
with "SAP BTP"

replace "SAP CP"
with "SAP BTP"

replace "SAP Mobile Services"
with "SAP Mobile Services"

2021-03-05 14:51 UTC, MichaelCzcz requested changes
Please make sure to use the correct tags. You can't simply replace the part that says "cloud" with "business-technology".
I have commented on some instances where you did this, but there are many more.
I will forward Daniel's email regarding BTP re-branding to you.

2021-03-05 14:51 UTC, MichaelCzcz commented on tutorials/cp-sdk-android-flows-custom-step/cp-sdk-android-flows-custom-step.md
> +primary_tag: products>sap-business-technology-platform-sdk-for-android
products>android-sdk-for-sap-btp

2021-03-05 14:51 UTC, MichaelCzcz commented on tutorials/cp-sdk-android-flows-restore/cp-sdk-android-flows-restore.md
> +primary_tag: products>sap-business-technology-platform-sdk-for-android
products>android-sdk-for-sap-btp
--

2021-03-05 14:51 UTC, MichaelCzcz commented on tutorials/cp-sdk-android-flows-stores/cp-sdk-android-flows-stores.md
> +primary_tag: products>sap-business-technology-platform-sdk-for-android
products>android-sdk-for-sap-btp
--

2021-03-05 14:51 UTC, MichaelCzcz commented on tutorials/cp-sdk-android-wizard-app-customize/cp-sdk-android-wizard-app-customize.md
> +primary_tag: products>sap-business-technology-platform-sdk-for-android
products>android-sdk-for-sap-btp

2021-03-05 14:51 UTC, MichaelCzcz commented on tutorials/cp-sdk-android-wizard-app-customize/cp-sdk-android-wizard-app-customize.md
> +tags: [  tutorial>beginner, operating-system>android, topic>mobile, topic>wizard, products>sap-business-technology-platform-sdk-for-android, products>sap-business-technology-platform ]
products>android-sdk-for-sap-btp

2021-03-05 14:51 UTC, MichaelCzcz commented on tutorials/cp-sdk-android-wizard-app-logging/cp-sdk-android-wizard-app-logging.md
> +tags: [  tutorial>beginner, operating-system>android, topic>mobile, products>sap-business-technology-platform-sdk-for-android, products>sap-business-technology-platform ]
products>android-sdk-for-sap-btp

2021-03-08 06:31 UTC, sandeep-tds commented
Hi Michael, 

Thank you for raising the issue. I will correct these tags and submit a new commit.

2021-03-31 06:24 UTC, sandeep-tds commented
Hi @thecodester, @MichaelCzcz 

@thecodester - I have made the changes we discussed. Can you please review the Pull Request and merge the changes? 
 
Thank you so much for your support.

2021-03-31 06:27 UTC, merged

2021-03-31 06:29 UTC, sandeep-tds commented
@thecodester  Thank you so much for the swift action. 

FYI @KevinMuessig  @flyingfish162 @FengHaoyue  - I've updated the tags for our tutorials and made all the rebranding changes. I am working on getting the community tag updated to our latest names. Once done, I will create a new PR. Thank you all so much for your support.