[MDK]: Updated tutorials with latest changes+added some validation Questions
SAPDocuments/Tutorials pull request #6576
Opened 2021-03-11 20:14 UTC by jitendrakansal

Updated MDK tutorials with latest changes+added some validation Questions

2021-03-15 07:55 UTC, MichaelCzcz requested changes

2021-03-15 07:55 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-build-client/cp-mobile-dev-kit-build-client.md
> +    >`AppName`: Provide a name for example: `DemoSampleApp`. It is the name of the application on the home screen of the device and it is also be the name of the folder where the client is created.
"... and it is also be the name..."

Please correct sentence.

2021-03-15 07:55 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-build-client/cp-mobile-dev-kit-build-client.md
> +    It is recommended that you copy this folder to another location so that you can to use it for future builds. Copy and paste it anywhere, and then rename template to `DemoSampleApp.mdkproject`.
"..., and then rename the template..."

2021-03-15 07:55 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-build-client/cp-mobile-dev-kit-build-client.md
> +    >To run the MDK client on Android emulator, you need to use `tns run android --emulator` command. Before trying to launch the client on Android emulator, make sure that you have already configure
"...you may get an error..."

2021-03-15 07:56 UTC, MichaelCzcz commented
@thecodester This PR contains two new tutorials. Please take over. Thank you.

2021-03-15 08:04 UTC, jitendrakansal commented
@MichaelCzcz thanks for your feedback/comments. I have updated and updated the PR.

2021-03-16 09:07 UTC, thecodester commented
@jitendrakansal How should we group the 2 new tutorials?

2021-03-17 17:07 UTC, jitendrakansal commented
@thecodester I did send you a separate email on this.
Anyway, here are the details:

1.  **cp-mobile-dev-kit-i18n-localization** should be part of [Level up with Mobile Development Kit](https://developers.sap.com/mission.mobile-dev-kit-level-up.html) mission , this tutorial should be added as **2nd last tutorial** in the list. 
![image](https://user-images.githubusercontent.com/31536700/111507625-218b3400-874b-11eb-85dd-11ff2e44463d.png)
 Also  please update **mission total time: 3 hr. 20 min**
2. **cp-mobile-dev-kit-cert-auth** should be part of [Brand Your customized App with Mobile Development Kit SDK](https://developers.sap.com/mission.mobile-dev-kit-brand.html) mission as **the last tutorial.**
also please update **mission total time: 1hr. 55 min**

2021-04-14 07:38 UTC, merged