Updated MDK tutorials
SAPDocuments/Tutorials pull request #6710
Opened 2021-05-19 18:18 UTC by jitendrakansal

Updated MDK tutorials

2021-05-20 06:57 UTC, MichaelCzcz requested changes

2021-05-20 06:57 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-map-extension/cp-mobile-dev-kit-map-extension.md
> +    >Files specifying in the `.mdkproject/App_Resources_Merge` folder overrides a part of the resource files in `<generated-project>/app/App_Resources`. You can find more details about it in [help do
Please check the first sentence. It is looking weird. May be a grammar issue.

2021-05-20 06:57 UTC, MichaelCzcz commented on tutorials/cp-mobile-dev-kit-map-extension/cp-mobile-dev-kit-map-extension.md
> +In this step, you will run the app on an android device.
Android

2021-05-21 06:20 UTC, MichaelCzcz commented
Did make any changes to line 502? The first sentence ("Files specifying in the...") still look weird. Did you want to say "specified"?

2021-05-21 06:22 UTC, jitendrakansal commented
@MichaelCzcz updated if say so. Please check

2021-05-21 06:59 UTC, merged