[Mobile Cards] Update Push cards tutorials
SAPDocuments/Tutorials pull request #6897
Opened 2021-08-05 15:39 UTC by sandeep-tds

Fixing the Push Tutorials after the single instance and multi-instance feature was released.

2021-08-06 06:12 UTC, MichaelCzcz requested changes
Hello @sandeep-tds, Thank you for your PR. Please correct those typos and I will merge your changes.

2021-08-06 06:12 UTC, MichaelCzcz commented on tutorials/cp-mobile-cards-create-sales-push/cp-mobile-cards-create-sales-push.md
> +  - how to modify the card type to single instance in Business Application Studio
Start with upper case.

2021-08-06 06:12 UTC, MichaelCzcz commented on tutorials/cp-mobile-cards-create-sales-push/cp-mobile-cards-create-sales-push.md
> +  - how to add subscription parameters to SAP Mobile cards
Start with upper case.

2021-08-06 06:12 UTC, MichaelCzcz commented on tutorials/cp-mobile-cards-create-sales-push/cp-mobile-cards-create-sales-push.md
> +  - how to deploy and publish a card to SAP Mobile Services from Business Application Studio
Start with upper case.

2021-08-06 06:12 UTC, MichaelCzcz commented on tutorials/cp-mobile-cards-push-sales-card/cp-mobile-cards-push-sales-card.md
> +  - how to push a card to your mobile device from an external system
Start with upper case.

2021-08-06 06:12 UTC, MichaelCzcz commented on tutorials/cp-mobile-cards-push-sales-card/cp-mobile-cards-push-sales-card.md
> +  - how to view and delete subscription cards on your mobile device
Start with upper case.

2021-08-11 09:19 UTC, thecodester commented
@sandeep-tds Also, when this is merged, let me know which groups/missions to label free tier

2021-08-12 06:05 UTC, merged