Update SDK js tutirials
SAPDocuments/Tutorials pull request #7012
Opened 2021-09-29 12:28 UTC by FrankEssenberger

2021-09-29 12:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAPDocuments/Tutorials?pullRequest=7012) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAPDocuments/Tutorials?pullRequest=7012) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAPDocuments/Tutorials?pullRequest=7012) it.</sub>

2021-09-29 13:27 UTC, artemkovalyov requested changes
I left my version in the suggestion. Let me know what you think.

2021-09-29 13:27 UTC, artemkovalyov commented on tutorials/cloudsdk-js-vdm-getall/cloudsdk-js-vdm-getall.md
> +> Up-to-date documentation is published on the [documentation portal](https://sap.github.io/cloud-sdk/)  of the SAP Cloud SDK.
```suggestion
> ### We migrate tutorials to our [documentation](https://sap.github.io/cloud-sdk/docs/js/getting-started)
> This tutorial is not actively maintained and might be partially outdated.
> Always up-to-date documentation is published on our [documentation portal](https://sap.github.io/cloud-sdk/docs/js/getting-started).
> We will provide a link to the updated version of this tutorial as soon as we release it.
```

2021-09-29 13:27 UTC, artemkovalyov commented on tutorials/cloudsdk-js-vdm-getall/cloudsdk-js-vdm-getall.md
> +> Up-to-date documentation is published on the [documentation portal](https://sap.github.io/cloud-sdk/)  of the SAP Cloud SDK.
I'd avoid using `DEPRECATED`. Many things a quite contextual, see my suggestion.

2021-09-29 19:38 UTC, artemkovalyov approved these changes
Thanks. Let's spread it around other tutorials.

2021-09-30 06:42 UTC, FrankEssenberger commented
@sacnl I wanted to add you as reviewer, but I could not assign more reviewer.

2021-09-30 14:16 UTC, merged