restructured information and added link to free tier tutorial
SAPDocuments/Tutorials pull request #7276
Opened 2021-12-03 07:26 UTC by AnnikaGonnermann

2021-12-03 07:39 UTC, MichaelCzcz requested changes

2021-12-03 07:39 UTC, MichaelCzcz commented on tutorials/btp-cockpit-setup/btp-cockpit-setup.md
> +    A plan limits the quantity of the service that's available.  Maybe you need a lot of some service in a production subaccount, and maybe you need less for development or test.  When you assign an
"...for develompent or test**ing**."

2021-12-03 07:41 UTC, AnnikaGonnermann commented on tutorials/btp-cockpit-setup/btp-cockpit-setup.md
> +    A plan limits the quantity of the service that's available.  Maybe you need a lot of some service in a production subaccount, and maybe you need less for development or test.  When you assign an
@MichaelCzcz: You are absolutely right!

2021-12-03 14:42 UTC, MichaelCzcz commented on tutorials/btp-cockpit-setup/btp-cockpit-setup.md
> +    A plan limits the quantity of the service that's available.  Maybe you need a lot of some service in a production subaccount, and maybe you need less for development or test.  When you assign an
Did you make the change?

2021-12-03 14:48 UTC, AnnikaGonnermann commented on tutorials/btp-cockpit-setup/btp-cockpit-setup.md
> +    A plan limits the quantity of the service that's available.  Maybe you need a lot of some service in a production subaccount, and maybe you need less for development or test.  When you assign an
now yes :)

2021-12-06 07:04 UTC, MichaelCzcz requested changes
Your branch has conflicts. I will merge it after you have resolved them.

2021-12-14 10:12 UTC, MichaelCzcz commented
@AnnikaGonnermann If you don't resolve those conflicts, I can't merge your PR.

2021-12-14 10:18 UTC, AnnikaGonnermann commented
@MichaelCzcz  I don't understand why Git shows the entire tutorial as one big conflict for me. I've deleted the conflict markers now, let's see what happens.

2021-12-17 07:23 UTC, closed without merging